# Generated by Django 4.1.3 on 2023-02-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(default='true', max_length=500)),
                ('Option1', models.CharField(default='true', max_length=100)),
                ('Option2', models.CharField(default='true', max_length=100)),
                ('Option3', models.CharField(default='true', max_length=100)),
                ('Option4', models.CharField(default='true', max_length=100)),
                ('Corrans', models.CharField(default='true', max_length=100)),
            ],
        ),
    ]
