# Generated by Django 4.1.3 on 2023-02-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alphabetseries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alphabetseries',
            old_name='Opt1',
            new_name='Op1',
        ),
    ]
