# Generated by Django 4.1.3 on 2023-02-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_opt1_alphabetseries_op1'),
    ]

    operations = [
        migrations.CreateModel(
            name='seatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ques1', models.CharField(default='true', max_length=500)),
                ('Op11', models.CharField(default='true', max_length=100)),
                ('Op12', models.CharField(default='true', max_length=100)),
                ('Op13', models.CharField(default='true', max_length=100)),
                ('Op14', models.CharField(default='true', max_length=100)),
                ('Corans1', models.CharField(default='true', max_length=100)),
            ],
        ),
    ]
