# Generated by Django 4.1.3 on 2023-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_seatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodrel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ques3', models.CharField(default='true', max_length=500)),
                ('Op31', models.CharField(default='true', max_length=100)),
                ('Op32', models.CharField(default='true', max_length=100)),
                ('Op33', models.CharField(default='true', max_length=100)),
                ('Op34', models.CharField(default='true', max_length=100)),
                ('Corans3', models.CharField(default='true', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ordrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ques2', models.CharField(default='true', max_length=500)),
                ('Op21', models.CharField(default='true', max_length=100)),
                ('Op22', models.CharField(default='true', max_length=100)),
                ('Op23', models.CharField(default='true', max_length=100)),
                ('Op24', models.CharField(default='true', max_length=100)),
                ('Corans2', models.CharField(default='true', max_length=100)),
            ],
        ),
    ]
