# Generated by Django 4.1.3 on 2023-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='True', max_length=50)),
                ('email', models.CharField(default='True', max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
