# Generated by Django 4.1.3 on 2023-01-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reasap1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='true', max_length=60)),
                ('mod', models.CharField(default='true', max_length=200)),
            ],
        ),
    ]
