# Generated by Django 4.1.3 on 2023-01-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reasap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reasap1',
            old_name='mod',
            new_name='mob',
        ),
    ]
