# Generated by Django 4.1.3 on 2023-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasap', '0002_rename_mod_reasap1_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicesec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(default='true', max_length=60)),
                ('content', models.CharField(default='true', max_length=300)),
            ],
        ),
    ]
