# Generated by Django 4.1.3 on 2023-01-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasap', '0003_servicesec'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursesec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(default='true', max_length=60)),
                ('sec1', models.CharField(default='true', max_length=50)),
                ('sec2', models.CharField(default='true', max_length=50)),
                ('sec3', models.CharField(default='true', max_length=50)),
                ('sec4', models.CharField(default='true', max_length=50)),
                ('sec5', models.CharField(default='true', max_length=50)),
            ],
        ),
    ]
