# Generated by Django 4.1.3 on 2023-02-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasap', '0004_coursesec'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutsec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(default='true', max_length=20)),
                ('disc', models.CharField(default='true', max_length=100)),
            ],
        ),
    ]
