# Generated by Django 4.1.3 on 2023-02-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasap', '0005_aboutsec'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesec',
            name='image1',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='ClassName/'),
        ),
        migrations.AddField(
            model_name='servicesec',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='reasap/'),
        ),
    ]
